# Generated by Django 3.1.3 on 2020-12-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20201208_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='orgin',
            new_name='origin',
        ),
    ]
